databases:
  - name: alter-studio
    databaseName: alter-studio
    user: alter-studio

services:
  - type: web
    name: alter-studio
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alter-studio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false